package com.gmail.nossr50.datatypes.ability;

public enum AbilityTargetType {
	SELF,
	BLOCKER,
	COMBAT_TARGET_ALL,
	COMBAT_TARGET_TOWER,
	COMBAT_TARGET_HERO,
	COMBAT_TARGET_HERO_OR_TOWER,
	GLOBAL_ALLIES,
	GLOBAL_ENEMIES,
	ALLIED_NEIGHBORS,
	ALLIED_NEIGHBORS_AND_SELF,
	ENEMY_NEIGHBORS,
	RANDOM_ENEMY_NEIGHBOR,
	RANDOM_ENEMY,
	COMBAT_TARGET_NEIGHBORS, //Neighbors of combat target
}
